services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:noble
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis:6.2-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  mongo-data:
  redis_data:
